server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/todo
    username: root
    password: rootpass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        health-check-path: /health
