server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB
    username: root
    password: rootpass
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true

